name: docker-publish
on:
  workflow_dispatch: # manually run
    inputs:
      packages:
        description: 'Comma-separated list of packages to publish to Docker Hub'
        required: true
        default: '*'
      graduate:
        description: 'Graduate from prerelease'
        required: false
        default: 'false'
      releaseTag:
        description: 'Tag the release (next, latest)'
        required: false
        default: 'next'


env:
  CI: true


jobs:
  publish:
    name: docker-publish
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker login
        if: "contains(github.event.inputs.packages, 'hydra-indexer') || github.event.inputs.packages == '*'"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish hydra-indexer image
        if: "contains(github.event.inputs.packages, 'hydra-indexer') || github.event.inputs.packages == '*'"
        run: ./scripts/docker-publish.sh hydra-indexer
        env:
          RELEASE_TAG: ${{ github.event.inputs.releaseTag }}

      - name: "Publish hydra-indexer-status-service image"
        if: "contains(github.event.inputs.packages, 'hydra-indexer-status-service') || github.event.inputs.packages == '*'"
        run: ./scripts/docker-publish.sh hydra-indexer-status-service
        env:
          RELEASE_TAG: ${{ github.event.inputs.releaseTag }}

      - name: Publish hydra-indexer-gateway image
        if: "contains(github.event.inputs.packages, 'hydra-indexer-gateway') || github.event.inputs.packages == '*'"
        run: ./scripts/docker-publish.sh hydra-indexer-gateway
        env:
          RELEASE_TAG: ${{ github.event.inputs.releaseTag }}

      - name: Publish hydra-moonriver-indexer-gateway image
        if: "contains(github.event.inputs.packages, 'hydra-moonriver-indexer-gateway') || github.event.inputs.packages == '*'"
        run: ./scripts/docker-publish.sh hydra-moonriver-indexer-gateway
        env:
          RELEASE_TAG: ${{ github.event.inputs.releaseTag }}
